public with sharing class TwilioCloudCommunicationClass { 
    public String getPersonList() {
        return null;
    }

 
      
    // Public Properties  
    public String SelectedMobileNumber{get;set;}  
    public String OtherMobileNumber{get;set;}  
    public String textMessage{get;set;}  
      
    // Default construtor  
    public TwilioCloudCommunicationClass()  
    {  
        SelectedMobileNumber  = '' ;  
        OtherMobileNumber = '' ;  
    }  
      
    
      
    public void SendSMS()  
    {  
  }
  }